### ISSUE TITLE
code for generating user dictionary CSV is missing fields

### ISSUE THREAD

**Issue by garfieldnate** [octanove/janlpbook-code#1]
The code for "the thorough approach" on page 4 of section 2.2 does not print the first four fields of the dictionary CSV (word, context node ID's and cost), so the resulting CSV dictionary does not work; MeCab accepts a smaller number of fields without complaint, so the issue isn't obvious until you inspect fugashi's output.

**Comment by polm** [comment]
Thanks for pointing that out, sorry about the miss! I'll get that updated. 

For the record, something like this should work:

```
prefix = f"{word},,,0,"
print(prefix + ",".join(entry.values()))
```

**Comment by garfieldnate** [comment]
Thanks for looking at this! I have to say, working through getting a dictionary working properly, it's still quite a pain. The TODO note [here](https://github.com/polm/fugashi/blob/master/fugashi/cli.py#L44) would be lovely, as would some kind of checking of the input file; the CSV doesn't use headers, so it's quite hard to inspect for correctness manually. For example, if the user is using unidic-lite for the system dictionary, you could check that the CSV has (roughly) the correct number of columns and that some of the types are correct (i.e. that the first column contains a non-empty string and not `*`).

**Comment by polm** [comment]
I've updated 2.2, so the PDF should have working code now. Thanks again for pointing this out.

About the dictionary vetting - thanks for the suggestion. I'll open an issue on the fugashi repo and take a look at it.

**Comment by garfieldnate** [comment]
Thanks again!
